apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: rollout-learning
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/saravana-93/argocd-gitops.git
    targetRevision: HEAD
    path: rollout-learning

  destination:
    server: https://kubernetes.default.svc
    namespace: rollout-learning

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
