# guestbook-ui/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  namespace: guestbook-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - name: guestbook-ui
          image: gcr.io/google-samples/gb-frontend:v5
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  namespace: guestbook-ui
spec:
  type: ClusterIP
  selector:
    app: guestbook-ui
  ports:
    - port: 80
      targetPort: 80
